#!/usr/bin/env bash
set -euo pipefail

# macOS prerequisites for Tauri desktop builds. Assumes Rust is already
# installed; this script only checks Xcode tools, installs Rust macOS targets,
# and installs/updates Tauri CLI.

MACOS_RUST_TARGETS=(
    aarch64-apple-darwin
    x86_64-apple-darwin
)

SCRIPT_DIR="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=scripts/libs/common.sh
source "${SCRIPT_DIR}/libs/common.sh"

# shellcheck source=scripts/libs/project-env.sh
source "${SCRIPT_DIR}/libs/project-env.sh"

# shellcheck source=scripts/libs/apple-env.sh
source "${SCRIPT_DIR}/libs/apple-env.sh"

# shellcheck source=scripts/libs/tauri-cli.sh
source "${SCRIPT_DIR}/libs/tauri-cli.sh"

usage() {
    cat <<'EOF_USAGE'
Usage: scripts/setup-macos-env.sh

Prepares the local macOS host for Tauri macOS desktop release builds:
  - verifies Xcode tools are available
  - installs macOS Rust targets for universal builds
  - installs/updates tauri-cli via cargo install

Rust itself is expected to already be installed.
EOF_USAGE
}

install_macos_rust_targets() {
    log_info "==> Installing Rust macOS targets"
    rustup target add "${MACOS_RUST_TARGETS[@]}"
}

write_macos_env_file() {
    mkdir -p -- "${BUILD_ROOT}/macos"
    write_file_if_changed "${BUILD_ROOT}/macos/env.sh" <<EOF_ENV
# Generated by scripts/setup-macos-env.sh
export APP_NAME_PLACEHOLDER_MACOS_DIST_ROOT="${DIST_ROOT}/macos"
EOF_ENV

    log_success "env file: ${BUILD_ROOT}/macos/env.sh"
}

main() {
    case "${1:-}" in
    -h | --help)
        usage
        return 0
        ;;
    '') ;;
    *) fail "Unexpected argument: ${1}" ;;
    esac

    apple_require_macos "macOS builds"
    require_cmd cargo
    require_cmd rustup
    apple_require_xcode_tools
    install_macos_rust_targets
    install_tauri_cli
    write_macos_env_file

    log_success "macOS build environment ready"
}

main "$@"
