#!/usr/bin/env bash
set -euo pipefail

# macOS/iOS prerequisites for Tauri iOS builds. Assumes Rust is already
# installed; this script only installs/checks iOS targets, CocoaPods, and Tauri CLI.

IOS_RUST_TARGETS=(
    aarch64-apple-ios
    aarch64-apple-ios-sim
    x86_64-apple-ios
)

BREW_PACKAGES=(
    cocoapods
)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

# shellcheck source=scripts/lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

# shellcheck source=scripts/lib/project-env.sh
source "$SCRIPT_DIR/lib/project-env.sh"

# shellcheck source=scripts/lib/apple-env.sh
source "$SCRIPT_DIR/lib/apple-env.sh"

# shellcheck source=scripts/lib/tauri-cli.sh
source "$SCRIPT_DIR/lib/tauri-cli.sh"

usage() {
    cat <<'EOF_USAGE'
Usage: scripts/setup-ios-env.sh

Prepares the local macOS host for Tauri iOS builds:
  - verifies full Xcode is available
  - installs missing Homebrew packages needed by Tauri iOS builds
  - installs iOS Rust targets
  - installs/updates tauri-cli via cargo install

Rust itself is expected to already be installed.
EOF_USAGE
}

install_ios_rust_targets() {
    step "Installing Rust iOS targets"
    rustup target add "${IOS_RUST_TARGETS[@]}"
}

write_ios_env_file() {
    ensure_dir "$BUILD_ROOT/ios"
    write_file_if_changed "$BUILD_ROOT/ios/env.sh" <<EOF_ENV
# Generated by scripts/setup-ios-env.sh
export APP_NAME_PLACEHOLDER_IOS_DIST_ROOT="$DIST_ROOT/ios"
EOF_ENV
    ok "env file: $BUILD_ROOT/ios/env.sh"
}

main() {
    case "${1:-}" in
    -h | --help)
        usage
        return 0
        ;;
    '') ;;
    *) fail "Unexpected argument: $1" ;;
    esac

    apple_require_macos "iOS builds"
    need_command cargo
    need_command rustup
    apple_require_full_xcode
    apple_install_brew_packages "${BREW_PACKAGES[@]}"
    install_ios_rust_targets
    install_tauri_cli
    write_ios_env_file

    ok "iOS build environment ready"
}

main "$@"
