#!/usr/bin/env bash
set -euo pipefail

# macOS/iOS prerequisites for Tauri iOS builds. Assumes Rust is already
# installed; this script only installs/checks iOS targets, CocoaPods, and Tauri CLI.

IOS_RUST_TARGETS=(
    aarch64-apple-ios
    aarch64-apple-ios-sim
    x86_64-apple-ios
)

BREW_PACKAGES=(
    cocoapods
)

SCRIPT_DIR="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=scripts/libs/common.sh
source "${SCRIPT_DIR}/libs/common.sh"

# shellcheck source=scripts/libs/project-env.sh
source "${SCRIPT_DIR}/libs/project-env.sh"

# shellcheck source=scripts/libs/apple-env.sh
source "${SCRIPT_DIR}/libs/apple-env.sh"

# shellcheck source=scripts/libs/tauri-cli.sh
source "${SCRIPT_DIR}/libs/tauri-cli.sh"

usage() {
    cat <<'EOF_USAGE'
Usage: scripts/setup-ios-env.sh

Prepares the local macOS host for Tauri iOS builds:
  - verifies full Xcode is available
  - installs missing Homebrew packages needed by Tauri iOS builds
  - installs iOS Rust targets
  - installs/updates tauri-cli via cargo install

Rust itself is expected to already be installed.
EOF_USAGE
}

install_ios_rust_targets() {
    log_info "==> Installing Rust iOS targets"
    rustup target add "${IOS_RUST_TARGETS[@]}"
}

write_ios_env_file() {
    mkdir -p -- "${BUILD_ROOT}/ios"
    write_file_if_changed "${BUILD_ROOT}/ios/env.sh" <<EOF_ENV
# Generated by scripts/setup-ios-env.sh
export APP_NAME_PLACEHOLDER_IOS_DIST_ROOT="${DIST_ROOT}/ios"
EOF_ENV
    log_success "env file: ${BUILD_ROOT}/ios/env.sh"
}

main() {
    case "${1:-}" in
    -h | --help)
        usage
        return 0
        ;;
    '') ;;
    *) fail "Unexpected argument: ${1}" ;;
    esac

    apple_require_macos "iOS builds"
    require_cmd cargo
    require_cmd rustup
    apple_require_full_xcode
    apple_install_brew_packages "${BREW_PACKAGES[@]}"
    install_ios_rust_targets
    install_tauri_cli
    write_ios_env_file

    log_success "iOS build environment ready"
}

main "$@"
